---

- name: Get vApp
  uri:
    url: "{{ api_host }}/api/query?type=vApp&filter=name=={{ vapp_name }}"
    headers:
      Accept: "application/*+xml;version= {{ api_version }}"
      Cookie: "{{ login.set_cookie }}"
    method: GET
    return_content: yes
  register: vapp_response

- debug:
    var: vapp_response

- name: Extract vm_href
  xml:
    xmlstring: "{{ vapp_response.content }}"
    xpath: "/n:QueryResultRecords/n:VAppRecord[@name='{{ vapp_name }}']"
    content: attribute
    attribute: href
    namespaces: "n={{ namespace }}"
  register: vapp_href

- debug:
    var: vapp_href.matches[0]['{http://www.vmware.com/vcloud/v1.5}VAppRecord']['href']

- name: PowerOn VMs
  uri:
    url: "{{ vapp_href.matches[0]['{http://www.vmware.com/vcloud/v1.5}VAppRecord']['href'] }}/power/action/powerOn"
    headers:
      Accept: "application/*+xml;version={{ api_version }}"
      Cookie: "{{ login.set_cookie }}"
    method: POST
    return_content: yes
    status_code: 202
  register: powerOn_result

- debug:
    var: powerOn_result

