---

- name: Extract Network href
  xml:
    xmlstring: "{{ org_info.content }}"
    xpath: "/n:Org/n:Link[@name='{{ org_network_name }}']"
    content: attribute
    attribute: href
    namespaces: "n={{ namespace }}"
  register: lan_href

- debug:
    var: lan_href.matches[0]['{http://www.vmware.com/vcloud/v1.5}Link']['href']
